const API_URL='/api/prices';
const $=s=>document.querySelector(s);
const keyword=$('#keyword'), limit=$('#limit'), results=$('#results'), status=$('#status');
let publicKey=localStorage.getItem('model-atlas-public-key')||'';
let privateKey=localStorage.getItem('model-atlas-private-key')||'';
$('#publicKey').value=publicKey;
$('#privateKey').value=privateKey;
$('#openSettings').onclick=()=>$('#settingsModal').showModal();
$('#togglePublicKey').onclick=()=>{$('#publicKey').value='';$('#publicKey').focus()};
$('#toggleKey').onclick=()=>{const input=$('#privateKey');input.type=input.type==='password'?'text':'password';$('#toggleKey').textContent=input.type==='password'?'Show':'Hide'};
$('#settingsForm').onsubmit=async e=>{if(e.submitter?.id==='saveSettings'){publicKey=$('#publicKey').value.trim();privateKey=$('#privateKey').value.trim();localStorage.setItem('model-atlas-public-key',publicKey);localStorage.setItem('model-atlas-private-key',privateKey);try{const response=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publicKey,privateKey})});if(!response.ok)throw new Error('Server rejected settings')}catch(error){status.textContent=error.message;status.classList.remove('hidden')}}};
$('#clearSearch').onclick=()=>{keyword.value='';keyword.focus()};
$('#searchButton').onclick=search;
keyword.addEventListener('keydown',e=>{if(e.key==='Enter')search()});
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function rateFor(tier,type){const rates=tier?.Rates||[];return rates.find(r=>(r.ChargeItem||'').toLowerCase()===type)||rates.find(r=>(r.ChargeItemDescriptionEn||'').toLowerCase().includes(type))||null}
function formatRate(rate){if(!rate)return '<span class="unit">—</span>';return `<div class="rate">${escapeHtml(rate.Price||'—')} ${escapeHtml(rate.Currency||'')}</div><div class="unit">${escapeHtml(rate.UnitEn||rate.Unit||'')}</div>`}
function render(models=[]){$('#resultCount').textContent=models.length;results.innerHTML=models.length?models.flatMap(model=>(model.Tiers?.length?model.Tiers:[{}]).map(tier=>{const input=rateFor(tier,'input'),output=rateFor(tier,'output');return `<tr><td><div class="model-name">${escapeHtml(model.ModelName||model.ModelId||'Unnamed model')}</div><div class="model-id">${escapeHtml(model.ModelId||'')}</div></td><td><span class="provider">${escapeHtml(model.Manufacturer||'Unknown')}</span></td><td><div class="tier">${escapeHtml(tier.DescriptionEn||tier.Description||'Standard')}</div><div class="condition">${escapeHtml(tier.Condition||'')}</div></td><td class="input-rate">${formatRate(input)}</td><td class="output-rate">${formatRate(output)}</td><td><button class="expand" title="View all rates">↗</button></td></tr>`})).join(''):`<tr class="empty"><td colspan="6"><div class="empty-icon">⌁</div><h3>No matching models</h3><p>Try a broader search term or check your API settings.</p></td></tr>`}
async function search(){status.classList.add('hidden');if(!publicKey||!privateKey){status.textContent='Add both your UCloud public key and private key in API settings before searching.';status.classList.remove('hidden');return}const button=$('#searchButton');button.disabled=true;button.innerHTML='Searching <span>…</span>';try{const params=new URLSearchParams({Keyword:keyword.value.trim(),Offset:'0',Limit:limit.value});const response=await fetch(`${API_URL}?${params}`);if(!response.ok)throw new Error(`Request failed (${response.status})`);const data=await response.json();if(Number(data.RetCode)!==0)throw new Error(data.Message||`API returned code ${data.RetCode}`);render(data.Models||[]);$('#lastUpdated').textContent=`Updated ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`}catch(error){status.textContent=`Unable to load prices: ${error.message}`;status.classList.remove('hidden');render([])}finally{button.disabled=false;button.innerHTML='Search prices <span>→</span>'}}
