const $=s=>document.querySelector(s),keyword=$('#keyword'),limit=$('#limit'),results=$('#results'),status=$('#status');
let publicKey='',privateKey='',bailianApiKey='';
async function loadSettings(){try{const r=await fetch('/api/settings');const d=await r.json();if(d.astraflowConfigured)publicKey='configured';if(d.bailianConfigured)bailianApiKey='configured'}catch{}}
void loadSettings();
$('#openSettings').onclick=()=>$('#settingsModal').showModal();
const toggle=(id,input)=>$(id).onclick=()=>{const e=$(input);e.type=e.type==='password'?'text':'password';$(id).textContent=e.type==='password'?'Show':'Hide'};
toggle('#toggleKey','#privateKey');toggle('#toggleBailianKey','#bailianApiKey');$('#togglePublicKey').onclick=()=>{$('#publicKey').value='';$('#publicKey').focus()};
$('#settingsForm').onsubmit=async e=>{if(e.submitter?.id==='saveSettings'){publicKey=$('#publicKey').value.trim();privateKey=$('#privateKey').value.trim();bailianApiKey=$('#bailianApiKey').value.trim();try{const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publicKey,privateKey,bailianApiKey})});if(!r.ok)throw Error('Server rejected settings')}catch(err){status.textContent=err.message;status.classList.remove('hidden')}}};
$('#clearSearch').onclick=()=>{keyword.value='';keyword.focus()};$('#searchButton').onclick=search;keyword.addEventListener('keydown',e=>{if(e.key==='Enter')search()});
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function card(platform,rate){if(!rate)return '<span class="missing">—</span>';return `<div class="price-platform ${platform.toLowerCase()}">${esc(rate.price||rate.Price||'—')} <small>${esc(rate.currency||rate.Currency||'')}</small></div><div class="unit">${esc(rate.price_unit||rate.UnitEn||rate.Unit||'')}</div>`}
function astraRows(data){return (data.Models||[]).map(m=>({name:m.ModelName||m.ModelId,id:m.ModelId,provider:m.Manufacturer,platform:'AstraFlow',tiers:m.Tiers||[]}))}
function baiRows(data){const models=data.output?.models||data.data||data.models||[];return models.map(m=>({name:m.model||m.id||m.name,id:m.model||m.id,provider:m.provider||m.inference_provider,platform:'Bailian',tiers:(m.prices||[]).map(p=>({DescriptionEn:p.range_name,Rates:(p.prices||[]).map(x=>({ChargeItem:x.type,Price:x.price,UnitEn:x.price_unit,ChargeItemDescription:x.price_name}))}))}))}
function rates(t){return {input:(t.Rates||[]).find(r=>String(r.ChargeItem).includes('input')),output:(t.Rates||[]).find(r=>String(r.ChargeItem).includes('output'))}}
function render(data){const platformErrors=[data.astraflow?.error?`AstraFlow: ${data.astraflow.error}`:'',data.bailian?.error?`Bailian: ${data.bailian.error}`:''].filter(Boolean);if(platformErrors.length){status.textContent=platformErrors.join('  |  ');status.classList.remove('hidden')}const groups=new Map();[...astraRows(data.astraflow),...baiRows(data.bailian)].forEach(m=>{const k=(m.name||'').toLowerCase();if(!groups.has(k))groups.set(k,[]);groups.get(k).push(m)});$('#resultCount').textContent=groups.size;results.innerHTML=groups.size?[...groups.values()].map(group=>{const name=group[0].name;return `<tr><td><div class="model-name">${esc(name)}</div><div class="model-id">${esc(group[0].id)}</div></td><td colspan="4"><div class="comparison">${group.map(m=>{const t=m.tiers[0]||{},r=rates(t);return `<div class="platform-price"><span class="provider ${m.platform==='Bailian'?'bailian':''}">${m.platform}</span><span class="provider-name">${esc(m.provider||'')}</span><span class="tier">${esc(t.DescriptionEn||'Standard')}</span><span class="price-cell input-rate"><b>IN</b>${card(m.platform,r.input)}</span><span class="price-cell output-rate"><b>OUT</b>${card(m.platform,r.output)}</span></div>`}).join('')}</div></td><td></td></tr>`}).join(''):`<tr class="empty"><td colspan="6"><div class="empty-icon">⌁</div><h3>No matching models</h3><p>Try a broader search or configure another platform.</p></td></tr>`}
async function search(){status.classList.add('hidden');if(!publicKey&&!bailianApiKey){status.textContent='Configure at least one platform in API settings.';status.classList.remove('hidden');return}const b=$('#searchButton');b.disabled=true;b.innerHTML='Searching <span>…</span>';try{const r=await fetch(`/api/prices?Keyword=${encodeURIComponent(keyword.value.trim())}&Limit=${limit.value}`);const d=await r.json();if(!r.ok)throw Error(d.message||'Request failed');render(d);$('#lastUpdated').textContent=`Updated ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`}catch(e){status.textContent=`Unable to load prices: ${e.message}`;status.classList.remove('hidden');render({})}finally{b.disabled=false;b.innerHTML='Search prices <span>→</span>'}}
